### ISSUE TITLE
Dataset Structure for running pretrained using this repo.

### ISSUE THREAD

**Issue by saifhassan** [ClaudiaShu/EMO_AffectNet#1]
Hey @ClaudiaShu,

Thank you for this repo.

Can you please guide, How pre-trained SSL-FER model can be used with this repo on FER2013/AffectNet dataset. Guide dataset structure for AffectNet/FER2013 please.

Thanks in advance.

**Comment by saifhassan** [comment]
Please add readme file if possible or guide here.

Thanks

**Comment by ClaudiaShu** [comment]
Hi, @saifhassan, I have just updated a readme to this repo and updated the data preprocessing files. 

You need to obtain the AffectNet dataset by request: http://mohammadmahoor.com/affectnet/. Upon acceptance, you may access the dataset. The assessment code accepts two kinds of input: .csv or hdf5. I have updated the data preprocessing code in this repo. 

For the evaluation with FER2013, please follow this repo: https://github.com/usef-kh/fer. 

Hope this is helpful and feel free to contact me if you have further questions!
